global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: mysql
    static_configs:
      - targets: ['prom_mysql_exporter:9104']
        labels:
          alias: mysql

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'phpfpm'
    scrape_interval: 2s
    scrape_timeout: 1s
    static_configs:
      - targets: ['exporter:9253']
